### ISSUE TITLE
invoke cite web error

### ISSUE THREAD

**Issue by lorinczz** [magnusmanske/listeria_rs#128]
src/reference.rs change causes Lua error due to invalid syntax.
Example https://hu.wikipedia.org/w/index.php?title=Wikip%C3%A9dia:Wikidata/Friss_hal%C3%A1lesetek&oldid=27296125
Changing to `{{#invoke:cite web||` fixes the issue according to https://en.wikipedia.org/wiki/Module:Cite_web.

**Comment by mbch331** [comment]
Issue also occurs on Dutch Wikipedia where we also don't have a module Cite web.
https://nl.wikipedia.org/w/index.php?title=Gebruiker:Spinster/Nederlandse_kunstenaars_publiek_domein_2017&curid=4752441&diff=67835146&oldid=67711921
And the solution isn't to create the module. Just because one wiki has a module, not all Wikipedias need to have that module.

**Comment by sjoerddebruin** [comment]
Any update on this?

**Comment by pere-prlpz** [comment]
Same issue in Catalan Wikipedia. We don't have module cite web but we could create it. However, the syntax ListeriaBot is using is not the same as https://en.wikipedia.org/wiki/Module:Cite_web, which requires a blank first parameter.

**Comment by pere-prlpz** [comment]
I've checked if the syntax error could be solved wiki side, but it seems [it can't.](https://ca.wikipedia.org/wiki/Plantilla_Discussi%C3%B3:Wikidata_list#c-Vriullop-20240805083500-Pere_prlpz-20240804150300)

Therefore, we (all wikis that can use cite web module) need ListeriaBot to fix the syntax and use || instead of | as [lorinczz](https://github.com/lorinczz) said 3 weeks ago.

**Comment by pere-prlpz** [comment]
I hate to insist on this but the option to add references looks great and it could do a lot to improve automatic lists, but to actually use it in any Wikipedia this bug needs to be fixed. I suppose developing the ref option took some non negligible amount of work, and the only think that seems to be needed in ListeriaBot to start using it is to change | with || when using invoke cite module.

**Comment by pere-prlpz** [comment]
And I don't even know the programming language used to write ListeriaBot, but my guess is that the line 117 of https://github.com/magnusmanske/listeria_rs/blob/master/src/reference.rs 

`"{{{{#invoke:cite web|url={}|title={}",`

should be replaced with:

`"{{{{#invoke:cite web||url={}|title={}",`

Can anybody check and do it, please? Thank you.

**Comment by vlakoff** [comment]
There are two different issues:
* What is mainly reported on this ticket: the [invoke call](https://github.com/magnusmanske/listeria_rs/blob/0b9879e8c7d2d3a1f73fc90156179f549e729a5d/src/reference.rs#L82) that is wrong for sure, as it is currently missing a function name (here, an empty string). Fixing this is straightforward.
* Some wikis don't have a "Cite web" module, and presumptively won't want to add it only for this use case. I was about to report that frwiki has this issue too (for instance on [this listing](https://fr.wikipedia.org/wiki/Projet:Wikidata/Listes/D%C3%A9c%C3%A8s_caus%C3%A9s_par_la_maladie_%C3%A0_coronavirus_2019)). Fixing this would probably be more difficult.

**Comment by magnusmanske** [comment]
Sorry it took me so long to work on this. I think the bot works correctly, as it is, on many wikis, so I believe a "blacklist" of some kind would suffice. Something like:
WIKI - USE_INVOKE - USE_CITE_WEB

Would that be sufficient?

What would be a list of wikis that need to go into that list?
From this thread I can see:
- huwiki
- nlwiki
- cawiki
Any others?

**Comment by vlakoff** [comment]
frwiki doesn't have the module, but has a [{{Cite web}}](https://fr.wikipedia.org/w/index.php?title=Mod%C3%A8le:Cite_web) template (which is a redirect to our locale template), and we do recognize English parameter names, in order to support the foreign articles that are imported without editing the templates.

**Comment by vlakoff** [comment]
How about automatically testing page existence on the wiki:
* if the module exists, use it.
* else if a template {{Cite web}} exists, use it.
* else as a fallback, build some basic wikicode, like `[<url> <title>], <website>, <access-date>`

But maybe it's not possible to automatically test and a manual list is required?

**Comment by magnusmanske** [comment]
I am going with the manual approach for now, can be amended later if it causes too much trouble.

**Comment by pere-prlpz** [comment]
In which wikis does the format {{#invoke:cite web| with a single bar works? As far as I know, this format doesn't work in any wiki, including enwiki. If it worked in some wikis we could just copy the same module in other wikis. That was the first approach but it didn't work.

**Comment by lorinczz** [comment]
It can't work, because it is invalid syntax.

**Comment by vlakoff** [comment]
Confirmed working on frwiki: https://fr.wikipedia.org/w/index.php?title=Projet:Wikidata/Listes/D%C3%A9c%C3%A8s_caus%C3%A9s_par_la_maladie_%C3%A0_coronavirus_2019&diff=prev&oldid=218399139

(The number format change is unrelated.)

**Comment by pere-prlpz** [comment]
In frwiki it uses now template cite web (instead of invoke cite web with a missing bar).

However, in cawiki it does not use cite web (https://ca.wikipedia.org/w/index.php?title=Viquip%C3%A8dia:P%C3%A0gina_de_proves&oldid=33904682) despite of it existing in cawiki. Please notice that the test I made include one reference that in frwiki is wrapped in cite web and in cawiki is just a bare url.

How can we make ListeriaBot to use template cite web in cawiki?
