### ISSUE TITLE
Killed by OS for overloading memory.

### ISSUE THREAD

**Issue by Tagishsimon** [magnusmanske/listeria_rs#53]
Listeria returned "Killed by OS for overloading memory." 

https://de.wikipedia.org/w/index.php?title=Benutzer:Sebastian_Wallroth/Spielwiese&oldid=207235792

Underlying SPARQL runs - 2878 results in 2495 ms

**Comment by SannitaSSJ** [comment]
Same bug as #35

**Comment by ratonyi** [comment]
Previously - until November 1 - updated, the query has not changed, since then it sends different messages back but the list is not updated (see also: https://www.wikidata.org/w/index.php?title=Wikidata:Wikivoyage/Lists/Embassies&action=history ). The last message to me was: Killed by OS for overloading memory.

Thank you for your help !

https://www.wikidata.org/wiki/Wikidata:Wikivoyage/Lists/Embassies

**Comment by AngryLoki** [comment]
Related discussion with some speculation and workaround: https://www.wikidata.org/wiki/Template_talk:Wikidata_list#Listeria_+_WikidataList_v2
(tldr: don't resolve country names with Listeria, use pure SPARQL for this).

**Comment by magnusmanske** [comment]
Fixed
